const valid_players = [
    {
        name: "TenZ",
        team: "Sentinels",
        role: "Duelist",
        agent1: "Jett",
        agent2: "KAY/O",
        agent3: "N/A",
    },
    {
        name: "Sacy",
        team: "Sentinels",
        role: "Initiator",
        agent1: "Skye",
        agent2: "Fade",
        agent3: "Sova",
    },

    {
        name: "saadhak",
        team: "LOUD",
        role: "Flex",
        agent1: "KAY/O",
        agent2: "Raze",
        agent3: "Viper",
    },
    {
        name: "tuyz",
        team: "LOUD",
        role: "Controller",
        agent1: "Omen",
        agent2: "Harbor",
        agent3: "Brimstone",
    },
    {
        name: "cauanzin",
        team: "LOUD",
        role: "Initiator",
        agent1: "Skye",
        agent2: "Sova",
        agent3: "Breach",
    },
    {
        name: "Less",
        team: "LOUD",
        role: "Sentinel",
        agent1: "Viper",
        agent2: "Killjoy",
        agent3: "N/A",
    },
    {
        name: "aspas",
        team: "LOUD",
        role: "Duelist",
        agent1: "Jett",
        agent2: "Neon",
        agent3: "Raze",
    },

    {
        name: "nAts",
        team: "Team Liquid",
        role: "Sentinel",
        agent1: "Cypher",
        agent2: "Killjoy",
        agent3: "Viper",
    },
    {
        name: "soulcas",
        team: "Team Liquid",
        role: "Initiator",
        agent1: "Fade",
        agent2: "KAY/O",
        agent3: "Skye",
    },
    {
        name: "Sayf",
        team: "Team Liquid",
        role: "Duelist",
        agent1: "Jett",
        agent2: "Raze",
        agent3: "N/A",
    },
    {
        name: "Redgar",
        team: "Team Liquid",
        role: "Controller",
        agent1: "Omen",
        agent2: "Brimstone",
        agent3: "N/A",
    },
    {
        name: "Jamppi",
        team: "Team Liquid",
        role: "Initiator",
        agent1: "Skye",
        agent2: "Breach",
        agent3: "Sova",
    },

    {
        name: "Boaster",
        team: "FNATIC",
        role: "Controller",
        agent1: "Astra",
        agent2: "Brimstone",
        agent3: "Omen",
    },
    {
        name: "Chronicle",
        team: "FNATIC",
        role: "Flex",
        agent1: "Viper",
        agent2: "Breach",
        agent3: "KAY/O",
    },
    {
        name: "Leo",
        team: "FNATIC",
        role: "Initiator",
        agent1: "Fade",
        agent2: "Skye",
        agent3: "Sova",
    },
    {
        name: "Derke",
        team: "FNATIC",
        role: "Duelist",
        agent1: "Raze",
        agent2: "Jett",
        agent3: "N/A",
    },
    {
        name: "Alfajer",
        team: "FNATIC",
        role: "Sentinel",
        agent1: "Killjoy",
        agent2: "Cypher",
        agent3: "N/A",
    },

    {
        name: "Jinggg",
        team: "PRX",
        role: "Duelist",
        agent1: "Raze",
        agent2: "Phoenix",
        agent3: "Sage",
    },
    {
        name: "mindfreak",
        team: "PRX",
        role: "Controller",
        agent1: "Astra",
        agent2: "Brimstone",
        agent3: "Omen",
    },
    {
        name: "f0rsakeN",
        team: "PRX",
        role: "Flex",
        agent1: "Harbour",
        agent2: "Neon",
        agent3: "Cypher",
    },
    {
        name: "d4v41",
        team: "PRX",
        role: "Flex",
        agent1: "Skye",
        agent2: "Viper",
        agent3: "Killjoy",
    },
    {
        name: "something",
        team: "PRX",
        role: "Duelist",
        agent1: "Jett",
        agent2: "Reyna",
        agent3: "N/A",
    },

    {
        name: "Boostio",
        team: "Evil Geniuses",
        role: "Sentinel",
        agent1: "Killjoy",
        agent2: "Astra",
        agent3: "N/A",
    },
    {
        name: "C0M",
        team: "Evil Geniuses",
        role: "Initiator",
        agent1: "Sova",
        agent2: "Viper",
        agent3: "Breach",
    },
    {
        name: "JAWGEMO",
        team: "Evil Geniuses",
        role: "Flex",
        agent1: "Raze",
        agent2: "Omen",
        agent3: "N/A",
    },
    {
        name: "Ethan",
        team: "Evil Geniuses",
        role: "Initiator",
        agent1: "Skye",
        agent2: "Breach",
        agent3: "KAY/O",
    },
    {
        name: "Demon1",
        team: "Evil Geniuses",
        role: "Duelist",
        agent1: "Jett",
        agent2: "Brimstone",
        agent3: "N/A",
    },

    {
        name: "crashies",
        team: "NRG",
        role: "Initiator",
        agent1: "Skye",
        agent2: "Sova",
        agent3: "N/A",
    },
    {
        name: "ardiis",
        team: "NRG",
        role: "Duelist",
        agent1: "Jett",
        agent2: "Killjoy",
        agent3: "Sage",
    },
    {
        name: "Victor",
        team: "NRG",
        role: "Flex",
        agent1: "Killjoy",
        agent2: "Raze",
        agent3: "KAY/O",
    },
    {
        name: "FNS",
        team: "NRG",
        role: "Flex",
        agent1: "Viper",
        agent2: "Breach",
        agent3: "Killjoy",
    },
    {
        name: "s0m",
        team: "NRG",
        role: "Controller",
        agent1: "Harbour",
        agent2: "Omen",
        agent3: "Astra",
    },

    {
        name: "MaKo",
        team: "DRX",
        role: "Controller",
        agent1: "Viper",
        agent2: "Omen",
        agent3: "Brimstone",
    },
    {
        name: "stax",
        team: "DRX",
        role: "Initiator",
        agent1: "Skye",
        agent2: "Breach",
        agent3: "KAY/O",
    },
    {
        name: "Rb",
        team: "DRX",
        role: "Flex",
        agent1: "Killjoy",
        agent2: "Harbour",
        agent3: "Neon",
    },
    {
        name: "Zest",
        team: "DRX",
        role: "Flex",
        agent1: "Sova",
        agent2: "Fade",
        agent3: "Harbour",
    },
    {
        name: "BuZz",
        team: "DRX",
        role: "Duelist",
        agent1: "Jett",
        agent2: "Killjoy",
        agent3: "Raze",
    },
];